[tools]
# Language runtimes
go = "1.26"
node = "24"
python = "3.12"
ruby = "4"
bun = "latest"
# java    = "openjdk-21"

# Aqua-managed binaries
# "aqua:golangci/golangci-lint" = "2.9.0"

# npm-managed CLIs
"npm:@biomejs/biome" = "latest"
"npm:@openai/codex" = "latest"
"npm:ctx7" = "latest"
# "npm:prettier"                  = "latest"
# "npm:typescript"                = "latest"
# "npm:typescript-language-server" = "latest"

[settings]
experimental = true
