#!/usr/bin/env zsh
# ============================================================================
# Git Wrapper Function
# ============================================================================
# Provides a convenient shorthand for git commands
# Usage:
#   g          # Runs 'git status'
#   g <args>   # Runs 'git <args>'

g() {
  if [[ $# -gt 0 ]]; then
    git "$@"
  else
    git status
  fi
}